version: '3'

services:
  labox:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8123:8123'
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - PORT=8123
      - HOST=0.0.0.0
